### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by Domosed-gamin** [JonVega/traffic#1]
Hi. Cool little game. Please add license file.

**Comment by Domosed-gamin** [comment]
no answer...

**Comment by JonVega** [comment]
Sorry about that! I will do that ASAP, thank you for bringing that up.

**Comment by JonVega** [comment]
Terribly sorry about the wait, but I've added a MIT license to the repo. Thanks for the heads up to do this, I never realized how important it is to implement a license, and will do so from now on!

Thanks again!
